In [1]:
import os
import pandas as pd

In [2]:
data_path = '/Users/romoluque_c/LEGEND/TAUP_evt_rate_ana/data_test/skimmed_files'

## Here I concatenate the skim dataframes for every run file for the chosen period

def read_and_concat_data(group, count, path=data_path):
    dfs = [pd.read_hdf(f'{path}/{group}_r{index:03d}_high_level.hdf')
           for index in range(count)]
    return pd.concat(dfs, verify_integrity=True)

data_p03 = read_and_concat_data('p03', 6)

In [3]:
data_p03

,is_muon_tagged,is_baseline,is_pulser,multiplicity,on_multiplicity,energy,energy_aux,is_usable_aoe,is_usable_aoe_aux,aoe,...,dt,dt_aux,lar_energy,lar_multiplicity,is_lar_rejected,lar_energy_dplms,lar_multiplicity_dplms,is_lar_rejected_dplms,lar_classifier,lar_time_shift
timestamp,,,,,,,,,,,,,,,,,,,,,
1.678596e+09,False,False,False,1,1,186.068592,0.000000,False,False,NaN,...,-54.249832,NaN,0.000000,0,False,1.149703,1,False,1.000000,53568.0
1.678596e+09,False,False,False,1,1,768.904629,0.000000,True,False,0.374784,...,687.018555,NaN,0.000000,0,False,0.000000,0,False,0.000000,NaN
1.678596e+09,False,False,False,1,1,110.688307,0.000000,True,False,-0.536870,...,617.150330,NaN,17.372586,7,True,17.239860,7,True,0.049540,47616.0
1.678596e+09,False,False,False,1,1,240.441997,0.000000,False,False,NaN,...,448.019897,NaN,10.260190,3,True,8.920335,3,True,0.104232,47872.0
1.678596e+09,False,True,False,0,0,0.000000,0.000000,False,False,NaN,...,NaN,NaN,0.000000,0,False,0.000000,0,False,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1.681386e+09,False,False,False,1,1,152.167161,0.000000,True,False,0.388312,...,544.145386,NaN,1.217464,1,False,1.230378,1,False,1.000000,51408.0
1.681386e+09,False,False,True,88,76,1130.600695,1242.536589,True,False,75.782618,...,173.752991,177.116531,39.641159,14,True,18.525361,7,True,0.411445,48976.0
1.681386e+09,False,False,False,1,1,208.783103,0.000000,True,False,-0.331237,...,462.889343,NaN,20.983399,11,True,21.161799,11,True,0.081626,47792.0
1.681386e+09,False,False,False,1,1,93.829161,0.000000,True,False,-0.019523,...,604.519226,NaN,12.525136,8,True,11.724832,8,True,0.118749,47584.0
1.681386e+09,False,False,False,1,1,98.527653,0.000000,True,False,-1.378554,...,1231.941528,NaN,0.000000,0,False,0.000000,0,False,0.000000,NaN

#### Each line of the skim files is one event

If you want to take for example events with multiplicity == 2: (all the flags named "aux" refer to the second detector that has register signal for that event)

In [4]:
data_p03[data_p03.multiplicity==2]

,is_muon_tagged,is_baseline,is_pulser,multiplicity,on_multiplicity,energy,energy_aux,is_usable_aoe,is_usable_aoe_aux,aoe,...,dt,dt_aux,lar_energy,lar_multiplicity,is_lar_rejected,lar_energy_dplms,lar_multiplicity_dplms,is_lar_rejected_dplms,lar_classifier,lar_time_shift
timestamp,,,,,,,,,,,,,,,,,,,,,
1.678596e+09,False,False,False,2,2,34.953276,107.659458,False,True,NaN,...,1102.299927,1245.521606,0.000000,0,False,0.000000,0,False,0.000000,NaN
1.678596e+09,False,False,False,2,2,97.446632,28.872404,True,False,-1.377104,...,1165.199219,1504.612183,0.530620,1,False,0.552738,1,False,0.000000,NaN
1.678596e+09,False,False,False,2,2,97.042014,25.390046,False,True,NaN,...,207.070358,54.578522,24.545150,13,True,23.311209,13,True,0.198668,48000.0
1.678596e+09,False,False,False,2,2,102.779448,36.087675,True,False,-1.509530,...,1243.740967,1459.885864,0.000000,0,False,0.000000,0,False,0.000000,NaN
1.678597e+09,False,False,False,2,2,96.028467,144.094483,True,True,-0.939765,...,818.522644,630.393250,27.432225,16,True,24.580194,16,True,0.171392,47504.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1.681386e+09,False,False,False,2,2,122.775803,31.838852,False,True,NaN,...,313.060883,-21.649466,0.000000,0,False,0.000000,0,False,0.000000,NaN
1.681386e+09,False,False,False,2,2,76.399335,26.001219,True,False,-0.794379,...,1180.331543,1017.848389,0.000000,0,False,0.000000,0,False,0.000000,NaN
1.681386e+09,False,False,False,2,1,51.979883,30.451187,False,False,NaN,...,-933.889160,-790.593506,12.284283,7,True,0.000000,0,False,0.600995,50784.0
1.681386e+09,False,False,False,2,2,111.109227,39.540706,True,False,-1.847326,...,1214.177612,1303.125000,0.000000,0,False,0.000000,0,False,0.000000,NaN
1.681386e+09,False,False,False,2,2,77.839935,102.915540,False,False,NaN,...,869.667480,894.714661,2.945175,1,False,3.079536,1,False,1.000000,54208.0